# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25fdf1c566b38ea2383d9558c95dd5874c71765fe8301c2f036402804bf7e13ca3d322fe0e9df77420676bd512a6a5404f614edb134d5229758934f4a41db271

test:
  secret_key_base: 2e66a5c0b110053b4d74813f862682e016ac904fc4484994fd0a8adfca29368a7cbbfb876c833944cf3ca0a304ada9b335b9397236481d3d63f5779cae40c3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 82a8ed1229a0e6a6c75489621d200cd09de1ac8e2cb3f3d9ad4e95e833acf185d36ce8c269bd233a3a648e8049fce5809e6f00cec10fb1b405b5710e44fdad62
